name: uniclass
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
    sdk: ^3.6.2

dependencies:
    bcrypt: ^1.1.3
    flutter:
        sdk: flutter
    google_sign_in: ^6.3.0
    provider: ^6.1.5
    supabase_flutter: ^2.8.4
    screenshot: ^3.0.0
    path_provider:
    share_plus:
    whatsapp_share2:

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/images/logoUnicv-removebg-preview.png
        - assets/images/Representacao-removebg-preview.png
        - assets/images/logo_uniclass_mobile.png
        - assets/images/fake_user_flutter.png
        - assets/images/moon_flutter.png
        - assets/images/fundo_celular.png
