name: uniclass
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  bcrypt: ^1.1.3
  google_sign_in: ^6.3.0
  supabase_flutter: ^2.8.4
  provider: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/unicv_logo_verde.png
    - assets/images/logoUnicv-removebg-preview.png
    - assets/images/Representacao-removebg-preview.png
